//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsRover.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarsRover.Common.RoverResources", typeof(RoverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Format Is Not Valid.
        /// </summary>
        public static string CommandNotValid {
            get {
                return ResourceManager.GetString("CommandNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Command Is Out Of Range.
        /// </summary>
        public static string CommandResultOutOfRange {
            get {
                return ResourceManager.GetString("CommandResultOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Position Is Not Empty/Valid.
        /// </summary>
        public static string CommandResultPositionNotValid {
            get {
                return ResourceManager.GetString("CommandResultPositionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover Output.
        /// </summary>
        public static string ExceptedOutput {
            get {
                return ResourceManager.GetString("ExceptedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there another rover ? (Y/N) :.
        /// </summary>
        public static string MessageAnotherRoute {
            get {
                return ResourceManager.GetString("MessageAnotherRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change a rover position ? (Y/N) :.
        /// </summary>
        public static string MessageChangeRoverPosition {
            get {
                return ResourceManager.GetString("MessageChangeRoverPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Rover At Position.
        /// </summary>
        public static string MessageFoundRover {
            get {
                return ResourceManager.GetString("MessageFoundRover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rover Position (X Y D) :.
        /// </summary>
        public static string MessageNewRoverPosition {
            get {
                return ResourceManager.GetString("MessageNewRoverPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Rover At Position.
        /// </summary>
        public static string MessageNotFoundRover {
            get {
                return ResourceManager.GetString("MessageNotFoundRover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover Command (LLMRMMRMLM) :.
        /// </summary>
        public static string MessageRoverCommand {
            get {
                return ResourceManager.GetString("MessageRoverCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Area Size (X Y) :.
        /// </summary>
        public static string MessageWorkingAreaSize {
            get {
                return ResourceManager.GetString("MessageWorkingAreaSize", resourceCulture);
            }
        }
    }
}
